/*
 * Dio_Lcfg.c
 *
 * Created: 01/04/2020 12:40:12 م
 *  Author: Ali makhlouf
 */ 


//link time configurations exist in this file
//an example of link time configurations is the array of structure that contains the pins and their corrsponding dio_IDs which is
//used in testing whether the id inserted is vald or not .

//this ans the dio-Cfg. file shall be generated by the configuation tool ( they aren't static)
//fo now we don't have a configuration tool so we assume the user has configured r pins so:
//#define PIN_NUM 4 in Dio_Cfg.h)
//and an array of structs shall contain 3 elements

#include "Dio.h"
#include "Dio_MemMap.h"


//link time configurations .. also for testing input parameters
channels_StructArrType channels[PINS_NUM] = {
	{LED, 1, 'A'},
	{BUZZER, 6, 'A'},
	{SW, 1, 'B'},
	{LED1, 0, 'B'}
};

ports_StructArrType ports[PORTS_NUM] = {
	{A, 'A'},
	{B, 'B'},
};

groups_StructArrType groups[GROUPS_NUM] = {
    
};
/*******************************************/
